<?php


namespace app\models;


use app\core\DbModel;

class Posts extends DbModel
{
    public string $post_title='';
    public string $post_image='';
    public string $post_details='';
    public string $category='';


    static function tableName(): string
    {
        return "temp_post";
    }


    function attributes(): array
    {
        return ['post_image','post_title','post_details','category'];
    }

    static function primaryKey(): string
    {
        return 'id';
    }

    function rulse(): array
    {
        return [
            'post_title'=>[self::RULE_REQUIRED],
            'post_image'=>[self::RULE_IMAGE],
            'post_details'=>[self::RULE_REQUIRED],
            'category'=>[self::RULE_REQUIRED]
        ];
    }

    public function save()
    {
        return parent::save(); // TODO: Change the autogenerated stub
    }
}