<?php


namespace app\models;


use app\core\DbModel;


class Students extends DbModel
{
    public string $firstname='';
    public string $middlename='';
    public string $lastname='';
    public string $phone='';
    public string $email='';
    public string $country='';
    public string $city='';
    public string $address='';
    public string $gender='';
    public string $bloodgroup='';
    public string $dob='';
    public string $doj='';
    public string $profile_picture='';
    public string $cover_photo='';
    public string $description='';
    public string $qualification='';
    public string $nick_name='';
    public string $scocial_media_link='';



    static function primaryKey(): string
    {
        return "id";
    }

    static function tableName(): string
    {
        return "students";
    }

    function attributes(): array
    {
        return ['firstname','middlename','lastname','phone','email','dob','address','bloodgroup'];
    }




    function rulse(): array
    {
        return [
            'firstname'=>[self::RULE_REQUIRED],
            'middlename'=>[self::RULE_REQUIRED],
            'lastname'=>[self::RULE_REQUIRED],
            'phone'=>[self::RULE_REQUIRED],
            'email'=>[self::RULE_REQUIRED,self::RULE_EMAIL,[self::RULE_UNIQUE,'class'=>self::class]],
            'dob'=>[self::RULE_REQUIRED],
            'address'=>[self::RULE_REQUIRED],
            'bloodgroup'=>[self::RULE_REQUIRED]
        ];
    }

    public function save()
    {
        return parent::save(); // TODO: Change the autogenerated stub
    }


}